import { Patient } from './patient';

export const PATIENTS: Patient[] = [
  { id: 'patient1',
    birthday: '00/00/0000',
    sex: 'm',
    race: 'caucasian',
    nationality: 'american',
    speech_ability: 'low',
    diagnosis: 'speech_impediment',
    therapist_id: 'therapist1',
    caregiver_id: 'caregiver1'},
  { id: 'patient2',
    birthday: '01/01/0001',
    sex: 'f',
    race: 'asian',
    nationality: 'chinese',
    speech_ability: 'high',
    diagnosis: 'stuttering',
    therapist_id: 'therapist2',
    caregiver_id: 'caregiver2'},

  { id: 'patient3',
    birthday: '02/02/0002',
    sex: 'm',
    race: 'hispanic',
    nationality: 'mexican',
    speech_ability: 'medium',
    diagnosis: 'apraxia',
    therapist_id: 'therapist3',
    caregiver_id: 'caregiver3'},

  { id: 'patient4',
    birthday: '06/22/2010',
    sex: 'm',
    race: 'caucasian',
    nationality: 'United States',
    speech_ability: 'low',
    diagnosis: 'apraxia',
    therapist_id: 'therapist4',
    caregiver_id: 'caregiver4'},

  { id: 'patient5',
    birthday: '06/22/2010',
    sex: 'm',
    race: 'caucasian',
    nationality: 'United States',
    speech_ability: 'low',
    diagnosis: 'apraxia',
    therapist_id: 'therapist4',
    caregiver_id: 'caregiver4'},

  { id: 'patient6',
    birthday: '06/22/2010',
    sex: 'm',
    race: 'caucasian',
    nationality: 'United States',
    speech_ability: 'low',
    diagnosis: 'apraxia',
    therapist_id: 'therapist4',
    caregiver_id: 'caregiver4'},

  { id: 'patient7',
    birthday: '06/22/2010',
    sex: 'm',
    race: 'caucasian',
    nationality: 'United States',
    speech_ability: 'low',
    diagnosis: 'apraxia',
    therapist_id: 'therapist4',
    caregiver_id: 'caregiver4'},

  { id: 'patient8',
    birthday: '06/22/2010',
    sex: 'm',
    race: 'caucasian',
    nationality: 'United States',
    speech_ability: 'low',
    diagnosis: 'apraxia',
    therapist_id: 'therapist4',
    caregiver_id: 'caregiver4'},

  { id: 'patient9',
    birthday: '06/22/2010',
    sex: 'm',
    race: 'caucasian',
    nationality: 'United States',
    speech_ability: 'low',
    diagnosis: 'apraxia',
    therapist_id: 'therapist4',
    caregiver_id: 'caregiver4'},

  { id: 'patient10',
    birthday: '06/22/2010',
    sex: 'm',
    race: 'caucasian',
    nationality: 'United States',
    speech_ability: 'low',
    diagnosis: 'apraxia',
    therapist_id: 'therapist4',
    caregiver_id: 'caregiver4'},

  { id: 'patient11',
    birthday: '06/22/2010',
    sex: 'm',
    race: 'caucasian',
    nationality: 'United States',
    speech_ability: 'low',
    diagnosis: 'apraxia',
    therapist_id: 'therapist4',
    caregiver_id: 'caregiver4'},

  { id: 'patient12',
    birthday: '06/22/2010',
    sex: 'm',
    race: 'caucasian',
    nationality: 'United States',
    speech_ability: 'low',
    diagnosis: 'apraxia',
    therapist_id: 'therapist4',
    caregiver_id: 'caregiver4'},
];
